; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
board_upload.flash_size = 16MB
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=3
lib_ldf_mode = deep+
lib_deps = 
	earlephilhower/ESP8266Audio@^1.9.7
	lovyan03/LovyanGFX@^1.1.16
	askuric/Simple FOC@2.3.2
	mathieucarbou/AsyncTCP@^3.2.14
	mathieucarbou/ESPAsyncWebServer@^3.3.11
	adafruit/Adafruit NeoPixel
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.0
	pu2clr/PU2CLR RDA5807@^1.1.8